name: AsyncAPI documents processing

on:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Generating HTML from my AsyncAPI document
        uses: asyncapi/cli@v2.16.0
        with:
          filepath: lobby-to-client/v1/asyncapi.yml

      - name: Deploy GH page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .