name: AsyncAPI documents processing

on:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Generating HTML from my AsyncAPI document
        uses: asyncapi/cli@v3.5.2
        with:
          command: render
          filepath: lobby-to-client/v1/asyncapi.yml
          template: '@asyncapi/html-template@v3.3.1'

      - name: Deploy GH page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .