name: AsyncAPI documents processing

on:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Generating HTML from my AsyncAPI document
        uses: asyncapi/cli@v3.5.2
        with:
          command: custom
          # full command string passed to `asyncapi <custom_command>`
          custom_command: 'generate fromTemplate ./lobby-to-client/v1/asyncapi.yml "@asyncapi/html-template@3.3.1" --use-new-generator -o ./output --param outFilename=index.html --param singleFile=true'

      - name: Deploy GH page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./output