name: AsyncAPI documents processing

on:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm install -g @asyncapi/cli

      - name: Generate HTML docs from AsyncAPI spec
        run: |
          npx asyncapi generate \
            fromTemplate ./lobby-to-client/v1/asyncapi.yml \
            @asyncapi/html-template@3.3.1 \
            -o ./output \
            --param outFilename=index.html \
            --param singleFile=true \
            --use-new-generator

      - name: Deploy GH page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./output